<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>CodeMeridian.Evolution.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeMeridian.Evolution.Application\CodeMeridian.Evolution.Application.csproj" />
    <ProjectReference Include="..\CodeMeridian.Evolution.Infrastructure\CodeMeridian.Evolution.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

</Project>
